config/routes.rb
Lgtrack::Application.routes.draw do
 
  resources :project_infos

  root :to => 'project_infos#new'
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

end

app/models/project_info.rb
class ProjectInfo < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :duration, :name, :user

  def self.create_me(combi, user)
  	pi = ProjectInfo.new
  	# parse combi entry
  	# should have the format: <duration> <projectname> <description>
  	# ^(\d*,?\.?\d*) (\w*) ([\s\w]*)$
  	parts = /^(\d*,?\.?\d*) (\w*) ([\s\w]*)$/.match(combi)
  	if parts.length == 4
	  	pi.duration = parts[1].to_f
	  	pi.name = parts[2]
	  	pi.description = parts[3]
	  	pi.user = user
  	else
  		#fail
  		pi = null
	end
	return pi
  end

  def self.grouped_by_project
	groups = ProjectInfo.select("name, created_at").order("created_at DESC").group(:name)
	ret = Hash.new
	groups.each{|g|
		ret[g.name] = ProjectInfo.where(:name => g.name).sum(:duration)
	}
	return ret;
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/project_infos_controller.rb
# encoding: utf-8
class ProjectInfosController < ApplicationController
  # GET /project_infos/new
  # GET /project_infos/new.json
  def new
    @project_infos = ProjectInfo.order("created_at DESC")
    @project_infos_grouped = ProjectInfo.grouped_by_project
  end

  # POST /project_infos
  # POST /project_infos.json
  def create
    project_info = ProjectInfo.create_me(params[:combi], current_user)
    project_info.save
    if ProjectInfo.find_by_name(project_info.name)
      is_neu = ""
    else
      is_neu = "neues "
    end

    flash[:notice] = "eintrag für #{is_neu}projekt #{project_info.name} angelegt"
    redirect_to root_path
  end

  # DELETE /project_infos/1
  # DELETE /project_infos/1.json
  def destroy
    @project_info = ProjectInfo.find(params[:id])
    @project_info.destroy

    respond_to do |format|
      format.html { redirect_to project_infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_infos_helper.rb
module ProjectInfosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.erb
      <footer>
        <p>&copy; dotob 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

app/views/layouts/_head.html.erb
  <head>
    <meta charset="utf-8">
    <title>lgtrack</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>

app/views/layouts/_navbar.html.erb
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">lgtrack</a>
          <ul class="nav">
            <!-- links? -->
          </ul>
          <div class="container nav-collapse">
            <ul class='nav pull-right'>
            <% if user_signed_in? %>
              <li> <%= link_to current_user.email, '#' %> </li>
              <li> <%= link_to content_tag('span', 'log out', :class => 'label label-important'), destroy_user_session_path, :method => :delete %> </li>
              <li> <%= image_tag "#{(request.ssl? ? 'https://secure' : 'http://www')}.gravatar.com/avatar/#{Digest::MD5.hexdigest current_user.email}?s=30", :style => 'padding-top:5px' %></li>
            <% else %>
              <li> <%= link_to('Login', new_user_session_path)  %>  </li>
            <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
  <%= render "layouts/head" %>
  <body>
  <%= render "layouts/navbar" %>
    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span4 offset4">
            <% flash.each do |name, msg| %>
              <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                <a class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
              </div>
            <% end %>
          </div>
        </div>
        
        <div class="row">
          <div class="span9">
            <%= yield %>
          </div>
        </div><!--/row-->
      </div><!--/content-->
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/project_infos/new.html.erb
<h1>neuen eintrag erstellen</h1>

<%= form_tag project_infos_path, :class => "form-inline" do %>
  </br>
  <%= text_field_tag "combi", nil, :placeholder => 'project info eintragen...', :class => "span6 einzug" %>
  <%= submit_tag("speichern", :class => "btn") %>
<% end %>
<div id="match" class="einzug"></div>

<h1>übersicht</h1>
<ul class="unstyled">
	<% @project_infos_grouped.each do |name, duration| %>
		<li class="einzug"><h3><%= duration %> : <%= name %></h3></li>
	<% end %>
</ul>

<h1>historie</h1>
<ul class="unstyled">
	<% @project_infos.each do |pi| %>
		<li class="einzug"><h3><%= pi.duration %> : <%= pi.name %> => <%= pi.description %> (<%= pi.user.name %>)</h3></li>
	<% end %>
</ul>